version: '3.8'

services:
  saasboilerplate.webapi:
    image: ${DOCKER_REGISTRY-}saasboilerplatewebapi
    build:
      context: .
      dockerfile: src/SaasBoilerplate.WebApi/Dockerfile
    ports:
      - "5000:8080"
      - "5001:8443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8443;http://+:8080
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=SaasBoilerplateDb;User Id=sa;Password=YourStrong(!)Password;TrustServerCertificate=True;
      - ConnectionStrings__RedisConnection=redis:6379
    depends_on:
      - sqlserver
      - redis

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong(!)Password
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  sqlvolume:
